POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{
    "text": "test post 1"
}

###
GET http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

###
GET http://localhost:3000/api/posts/636683b6b7a919666cf935cd HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/posts/636683b6b7a919666cf935cd HTTP/1.1
content-type: application/json

{
    "id": "636683b6b7a919666cf935cd",
    "text": "test"
}

###

DELETE http://localhost:3000/api/posts/636685ba0b87a4fc0343c90d HTTP/1.1
content-type: application/json

###